#!/bin/bash

set -eu

mydir=$(dirname "$0")

#case $(git status --porcelain --untracked-files=no) in
#    "") ;;
#    *) echo "ERROR: Current working copy has been modified - not proceeding"; e#xit 2;;
#esac

mkdir -p packages

if [ -d /Applications ]; then   # Mac

    "$mydir"/macos/deploy.sh

else                            # Linux

    "$mydir"/linux/package.sh

fi


