name: Linux CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git mercurial mlton libboost-math-dev meson ninja-build
    - name: repoint
      run: ./repoint install
    - name: configure
      run: meson setup build
    - name: make
      run: |
        ninja -C build
        cp build/expressive-means.so .
    - name: archive
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: |
          expressive-means.so
          expressive-means.cat
          expressive-means.n3

