name: macOS CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: deps
      run: brew install polyml boost meson ninja mercurial
    - name: repoint
      run: ./repoint install
    - name: configure
      run: meson setup build
    - name: make
      run: |
        ninja -C build
        cp build/expressive-means.dylib .
    - name: archive
      uses: actions/upload-artifact@v3
      with:
        name: plugin
        path: |
          expressive-means.dylib
          expressive-means.cat


